###### Explore a compression algorithm to find the most common kmers


from sksequitur import parse

sequence = 'KKYGNDEKEEEKKYGKDEKEEEKKYGKDEKEEEKKYGNEKEEEKKYGKDEKEEEKKYGSDEKEKKYGNDEKEEEKKYGKDEKEEEKKYGKDEKEEEKKYGSDEKEKEKKYGSDDKEEEKKYGNDEKEKEKKYDSDDKEKEKKYGSDEKEKEKKYGNDEKEKEKKYDSDDKEKEKKYGSDEKEKEKKYGSDENEKEESGKESGGHE'
grammar = parse(sequence)
print(grammar)